from __future__ import annotations

import html
import json
import re
import zipfile
from datetime import datetime, timezone
from io import BytesIO
from uuid import uuid4

from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill
from openpyxl.utils import get_column_letter

from config import settings
from services.excel_service import escape_formula_injection
from services.storage_service import StorageService


DOCX_CONTENT_TYPE = "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
XLSX_CONTENT_TYPE = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
PDF_CONTENT_TYPE = "application/pdf"


def safe_download_name(name: str, extension: str) -> str:
    base = re.sub(r"[^A-Za-z0-9._ -]+", "_", name or "excelai-output").strip(" ._")
    if not base:
        base = "excelai-output"
    if not base.lower().endswith(f".{extension}"):
        base = f"{base}.{extension}"
    return base[:180]


def _docx_paragraph(text: str, style: str | None = None) -> str:
    style_xml = f'<w:pPr><w:pStyle w:val="{style}"/></w:pPr>' if style else ""
    return f"<w:p>{style_xml}<w:r><w:t xml:space=\"preserve\">{html.escape(text or '')}</w:t></w:r></w:p>"


def _docx_table(headers: list[str], rows: list[list[str]]) -> str:
    if not headers:
        return ""
    table_rows = [headers] + rows[:200]
    row_xml = []
    for row in table_rows:
        cells = []
        for value in row[: len(headers)]:
            cells.append(
                "<w:tc><w:tcPr><w:tcW w:w=\"2400\" w:type=\"dxa\"/></w:tcPr>"
                f"<w:p><w:r><w:t>{html.escape(str(value or ''))}</w:t></w:r></w:p></w:tc>"
            )
        row_xml.append(f"<w:tr>{''.join(cells)}</w:tr>")
    return (
        "<w:tbl><w:tblPr><w:tblStyle w:val=\"TableGrid\"/>"
        "<w:tblW w:w=\"0\" w:type=\"auto\"/></w:tblPr>"
        f"{''.join(row_xml)}</w:tbl>"
    )


def build_docx(title: str, content: str, table_headers: list[str] | None = None, table_rows: list[list[str]] | None = None) -> bytes:
    table_headers = table_headers or []
    table_rows = table_rows or []
    body_parts = [_docx_paragraph(title or "ExcelAI Report", "Title")]
    for line in (content or "").splitlines():
        stripped = line.strip()
        if not stripped:
            body_parts.append(_docx_paragraph(""))
        elif stripped.endswith(":") and len(stripped) <= 80:
            body_parts.append(_docx_paragraph(stripped, "Heading1"))
        else:
            body_parts.append(_docx_paragraph(stripped))
    body_parts.append(_docx_table(table_headers, table_rows))
    body_parts.append(_docx_paragraph(""))
    body_parts.append(_docx_paragraph(f"Generated by ExcelAI at {datetime.now(timezone.utc).isoformat()}"))
    document_xml = (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">'
        f"<w:body>{''.join(body_parts)}<w:sectPr><w:pgSz w:w=\"11906\" w:h=\"16838\"/>"
        '<w:pgMar w:top="1440" w:right="1440" w:bottom="1440" w:left="1440"/></w:sectPr></w:body></w:document>'
    )
    content_types = (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">'
        '<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>'
        '<Default Extension="xml" ContentType="application/xml"/>'
        f'<Override PartName="/word/document.xml" ContentType="{DOCX_CONTENT_TYPE}.main+xml"/>'
        "</Types>"
    )
    rels = (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
        '<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/>'
        "</Relationships>"
    )
    styles = (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">'
        '<w:style w:type="paragraph" w:styleId="Title"><w:name w:val="Title"/><w:rPr><w:b/><w:sz w:val="32"/></w:rPr></w:style>'
        '<w:style w:type="paragraph" w:styleId="Heading1"><w:name w:val="heading 1"/><w:rPr><w:b/><w:sz w:val="26"/></w:rPr></w:style>'
        "</w:styles>"
    )
    buffer = BytesIO()
    with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED) as docx:
        docx.writestr("[Content_Types].xml", content_types)
        docx.writestr("_rels/.rels", rels)
        docx.writestr("word/document.xml", document_xml)
        docx.writestr("word/styles.xml", styles)
    return buffer.getvalue()


def _style_sheet(ws):
    ws.freeze_panes = "A2"
    fill = PatternFill("solid", fgColor="D9EAD3")
    for cell in ws[1]:
        cell.font = Font(bold=True)
        cell.fill = fill
    for column_cells in ws.columns:
        max_len = max(len(str(cell.value or "")) for cell in column_cells)
        ws.column_dimensions[get_column_letter(column_cells[0].column)].width = min(max(max_len + 2, 12), 48)


def build_xlsx(sheets: dict[str, tuple[list[str], list[list]]]) -> bytes:
    workbook = Workbook()
    default = workbook.active
    workbook.remove(default)
    sheets = dict(sheets)
    if "Metadata" not in sheets:
        sheets["Metadata"] = (
            ["Key", "Value"],
            [
                ["generated_by", "ExcelAI"],
                ["generated_at", datetime.now(timezone.utc).isoformat()],
                ["export_quality", "formula_injection_escaped"],
            ],
        )
    for raw_title, (headers, rows) in sheets.items():
        title = re.sub(r"[:\\/?*\[\]]+", "_", raw_title or "Sheet")[:31]
        ws = workbook.create_sheet(title=title or "Sheet")
        ws.append([escape_formula_injection(value) for value in headers])
        for row in rows:
            ws.append([escape_formula_injection(value) for value in row])
        _style_sheet(ws)
    buffer = BytesIO()
    workbook.save(buffer)
    return buffer.getvalue()


def build_pdf(title: str, lines: list[str]) -> bytes:
    safe_lines = [str(title or "ExcelAI Report")[:100]] + [str(line or "")[:120] for line in lines[:44]]
    safe_lines.append(f"Generated by ExcelAI at {datetime.now(timezone.utc).isoformat()}")
    objects: list[bytes] = []
    stream_lines = ["BT", "/F1 18 Tf", "72 760 Td", f"({ _pdf_text(safe_lines[0]) }) Tj", "/F1 10 Tf"]
    for line in safe_lines[1:]:
        stream_lines.append("0 -18 Td")
        stream_lines.append(f"({_pdf_text(line)}) Tj")
    stream_lines.append("ET")
    stream = "\n".join(stream_lines).encode("latin-1", errors="replace")
    objects.append(b"<< /Type /Catalog /Pages 2 0 R >>")
    objects.append(b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>")
    objects.append(b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>")
    objects.append(b"<< /Length " + str(len(stream)).encode() + b" >>\nstream\n" + stream + b"\nendstream")
    objects.append(b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>")
    output = BytesIO()
    output.write(b"%PDF-1.4\n")
    offsets = [0]
    for index, obj in enumerate(objects, start=1):
        offsets.append(output.tell())
        output.write(f"{index} 0 obj\n".encode())
        output.write(obj)
        output.write(b"\nendobj\n")
    xref = output.tell()
    output.write(f"xref\n0 {len(objects) + 1}\n".encode())
    output.write(b"0000000000 65535 f \n")
    for offset in offsets[1:]:
        output.write(f"{offset:010d} 00000 n \n".encode())
    output.write(f"trailer << /Size {len(objects) + 1} /Root 1 0 R >>\nstartxref\n{xref}\n%%EOF".encode())
    return output.getvalue()


def _pdf_text(value: str) -> str:
    return value.encode("latin-1", errors="replace").decode("latin-1").replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)")


def store_output(
    db,
    user_id: str,
    content: bytes,
    display_name: str,
    output_type: str,
    operation_type: str,
    content_type: str,
    source_file_id: str | None = None,
    metadata: dict | None = None,
    workspace_id: str | None = None,
) -> dict:
    output_id = str(uuid4())
    extension = "docx" if output_type == "docx" else "pdf" if output_type == "pdf" else "xlsx"
    safe_name = safe_download_name(display_name, extension)
    storage_path = f"{user_id}/outputs/{output_id}_{safe_name}"
    StorageService(db).upload_bytes(storage_path, content, content_type)
    row = {
        "id": output_id,
        "user_id": user_id,
        "source_file_id": source_file_id,
        "output_type": output_type,
        "operation_type": operation_type,
        "display_name": safe_name,
        "storage_path": storage_path,
        "content_type": content_type,
        "metadata": json.dumps(metadata or {}),
        "workspace_id": workspace_id,
        "created_at": datetime.now(timezone.utc).isoformat(),
    }
    response = db.table("output_files").insert(row).execute()
    return response.data[0] if response.data else row
